name: whalelogic-io
region: nyc
services:
  - name: web
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_size_slug: basic-xxs
    instance_count: 1
    github:
      repo: whalelogic/hugo
      branch: main
      deploy_on_push: true
    routes:
      - path: /
    envs:
      - key: HUGO_ENV
        value: production

